- name: setting prompt
  become: true
  ansible.builtin.shell: set-prompt

- name: pinging the system 
  ansible.builtin.ping:
    
- name: print message
  ansible.builtin.debug:
    msg: Hello World

